### ISSUE TITLE
[BUG] Installing requirements.txt fails

### ISSUE THREAD

**Issue by spojordan** [da-rth/yasb#132]
## Expected Behavior
Installs should go smoothly.

## Current Behavior
Install fails with an error

## Possible Solution
A way to install the dependencies separately

## Steps to Reproduce
1. Make a txt file called **requirements.txt** with the stuff listed at https://github.com/da-rth/yasb/blob/main/requirements.txt
2. Open a terminal with Python installed
3. Type **pip install -r requirements.txt**

## Context (Environment)
I'm trying to install this status bar on Windows but encountering a bunch of issues. If there's a better bar with a simpler set up let me know.
```
pip install -r .\requirements.txt
Collecting BlurWindow==1.2.1 (from -r .\requirements.txt (line 1))
  Using cached BlurWindow-1.2.1-py3-none-any.whl.metadata (2.2 kB)
Collecting Cerberus==1.3.4 (from -r .\requirements.txt (line 2))
  Using cached Cerberus-1.3.4.tar.gz (63 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cssutils==2.5.1 (from -r .\requirements.txt (line 3))
  Using cached cssutils-2.5.1-py3-none-any.whl.metadata (9.3 kB)
Collecting humanize==4.3.0 (from -r .\requirements.txt (line 4))
  Using cached humanize-4.3.0-py3-none-any.whl.metadata (7.7 kB)
Collecting psutil==5.9.1 (from -r .\requirements.txt (line 5))
  Using cached psutil-5.9.1.tar.gz (479 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting PyQt6==6.3.1 (from -r .\requirements.txt (line 6))
  Using cached PyQt6-6.3.1-cp37-abi3-win_amd64.whl.metadata (2.2 kB)
Collecting pytz==2022.1 (from -r .\requirements.txt (line 7))
  Using cached pytz-2022.1-py2.py3-none-any.whl.metadata (21 kB)
Collecting pywin32==306 (from -r .\requirements.txt (line 8))
  Using cached pywin32-306-cp312-cp312-win_amd64.whl.metadata (6.5 kB)
Collecting PyYAML==6.0 (from -r .\requirements.txt (line 9))
  Using cached PyYAML-6.0.tar.gz (124 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [54 lines of output]
      running egg_info
      writing lib\PyYAML.egg-info\PKG-INFO
      writing dependency_links to lib\PyYAML.egg-info\dependency_links.txt
      writing top-level names to lib\PyYAML.egg-info\top_level.txt
      Traceback (most recent call last):
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in   ##get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
          self.run_setup()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 288, in <module>
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\dist.py", line 963, in run_command
          super().run_command(command)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 321, in run
          self.find_sources()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 329, in find_sources
          mm.run()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 550, in run
          self.add_defaults()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\command\egg_info.py", line 588, in add_defaults
          sdist.add_defaults(self)
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\command\sdist.py", line 102, in add_defaults
          super().add_defaults()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 251, in add_defaults
          self._add_defaults_ext()
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\_distutils\command\sdist.py", line 336, in _add_defaults_ext
          self.filelist.extend(build_ext.get_source_files())
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "<string>", line 204, in get_source_files
        File "C:\Users\User\AppData\Local\Temp\pip-build-env-kuxmj8lu\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 107, in __getattr__
          raise AttributeError(attr)
      AttributeError: cython_sources
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by spojordan** [comment]
This was fixed by installing a version of Python 3.10.
