### ISSUE TITLE
[BUG] When launching with python src/main.py

### ISSUE THREAD

**Issue by Na0ss** [da-rth/yasb#147]
Soo i did everything perfectly, but now when launching the program i get those "errors" :

`Traceback (most recent call last):
  File "C:\Users\noamr\yasb\src\main.py", line 3, in <module>
    from core.bar_manager import BarManager
  File "C:\Users\noamr\yasb\src\core\bar_manager.py", line 7, in <module>
    from core.bar import Bar
  File "C:\Users\noamr\yasb\src\core\bar.py", line 8, in <module>
    from BlurWindow.blurWindow import GlobalBlur
ModuleNotFoundError: No module named 'BlurWindow'`

So uh yeah, please help me !

**Comment by abickiya** [comment]
I'm getting this exact same message, no display. Running Python 3.12.4, wondering if that could be an issue.

**Comment by Nyxendoescode** [comment]
same thing going on my pc too.

**Comment by idktikoiguess** [comment]
i got this problem too has anyone found a fix yet??
